import type { NextPage } from 'next';

import Head from 'next/head';

import HomePage from '../components/Home';

const Home: NextPage = ({ slots, workers, availableWorkers }: any) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage
        availableWorkers={availableWorkers}
        workers={workers}
        slots={slots}
      />
    </>
  );
};
export default Home;

export const getStaticProps = async () => {
  const resSlots = await fetch(
    'https://storage.googleapis.com/urban-technical/slots.json'
  );
  const resWorkers = await fetch(
    'https://storage.googleapis.com/urban-technical/workers.json'
  );
  const resAvailableWorkers = await fetch(
    'https://storage.googleapis.com/urban-technical/available-workers.json'
  );
  const slots = await resSlots.json();
  const workers = await resWorkers.json();
  const availableWorkers = await resAvailableWorkers.json();

  return {
    props: {
      slots,
      workers,
      availableWorkers,
    },
  };
};
