import type { NextPage } from 'next';

import Head from 'next/head';

import HomePage from '../components/Home';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Property Search Provider</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </>
  );
};
export default Home;
